[project]
name = "casbin-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "casbin>=1.3.0",
    "fastapi>=0.104.1",
    "python-multipart>=0.0.6",
    "sqlmodel>=0.0.22",
    "uvicorn>=0.24.0",
]
